### ISSUE TITLE
Team (about page) section fix 

### ISSUE THREAD

**Issue by armarinac** [acidjazz/oneconcern#10]
Can we please adjust this to read left to right: 
Team | Board of Directors | Advisors & Investors 

![screen shot 2018-01-30 at 9 44 30 am](https://user-images.githubusercontent.com/35855331/35582001-4fa358be-05a2-11e8-889d-771ef840bdc3.png)

Default still needs to be on "Team"

**Comment by acidjazz** [comment]
On it!
