### ISSUE TITLE
Mobile tweaks

### ISSUE THREAD

**Issue by armarinac** [acidjazz/oneconcern#11]
1. Can we shorten white underline on mobile?
![img_8009](https://user-images.githubusercontent.com/35855331/35582232-0ec064c6-05a3-11e8-9b84-0938a9c184ab.PNG)

2. Can we align buttons (make consistent), and make all buttons same size?
![img_8011](https://user-images.githubusercontent.com/35855331/35582242-1ae2feb2-05a3-11e8-894c-8a370433f3c9.PNG)

**Comment by acidjazz** [comment]
1 - yes
2 - sure, i'd also rather have this menu be full screen as well.

**Comment by acidjazz** [comment]
fixed in PR #13
