### ISSUE TITLE
blue bar on top of pages

### ISSUE THREAD

**Issue by armarinac** [acidjazz/oneconcern#20]
When you click the nav bar, it looks like a light blue line is coming across top of page. I've not seen this happening before.

**Comment by acidjazz** [comment]
This is a general loading animation I've placed to help give instant satisfaction, if you want I can make it any other color. 

For now I'll change it to one of the colors based on the style guide.

**Comment by armarinac** [comment]
Okay cool. Ya can we change it to the dark blue/grey from style guide? That might be best.
