### ISSUE TITLE
product page countup animation from 2.5s to 3s

### ISSUE THREAD

**Issue by acidjazz** [acidjazz/oneconcern#46]

**Comment by armarinac** [comment]
Correction – it's at 3s and we'd like to change to 2.5s

**Comment by acidjazz** [comment]
@armarinac thanks, i got it right in the code

**Comment by armarinac** [comment]
One comment from Dara is the number animations on product page – can that viewpoint animation be only once as well ?

**Comment by acidjazz** [comment]
@armarinac done!
